# Generated by Django 4.2.8 on 2024-01-23 13:01
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("address", models.CharField(max_length=100)),
                ("postal_code", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("products", models.ManyToManyField(to="products.product")),
            ],
        ),
    ]
