# Generated by Django 4.2.8 on 2024-03-19 14:20
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_order_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="completed",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="order",
            name="receipt",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
