# Generated by Django 4.2.8 on 2024-03-19 14:36
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_order_completed_order_image_order_receipt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="completed",
            field=models.BooleanField(default=False),
        ),
    ]
