FROM rust:1.80.0-slim

ENV RUST_BACKTRACE=1 CARGO_BUILD_TARGET="x86_64-unknown-linux-gnu"

ADD https://github.com/pypa/hatch/releases/latest/download/hatch-x86_64-unknown-linux-gnu.tar.gz /tmp

RUN tar -C /usr/local/bin -xzf /tmp/hatch-x86_64-unknown-linux-gnu.tar.gz \
  && cargo install just

CMD ["tail", "-f", "/dev/null"]
