name: CI

on: [ push, pull_request, workflow_dispatch ]

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install uv
        uses: astral-sh/setup-uv@v3
      - name: Run tests
        run: uv sync && uvx pytest

